### ISSUE TITLE
Membrane potential not being initialized correctly

### ISSUE THREAD

**Issue by bmerrihort** [LEMS/pylems#20]
I am trying to get to grips with NeuroML2/LEMS, and have run into what seems to be a bug in PyLEMS when running a very simple model of a single compartment neuron with just a passive leak channel. 

MyCell.xml: http://pastebin.com/RVNb3m2s
MySim.xml: http://pastebin.com/L2N8A3Ht

No matter what value I specify for initMembPotential, in the results the membrane potential always appears to start at 0mV. I know it's using initMembPotential somehow, because I get an error if I remove it! It's entirely possible I've messed something up in my model files, but I don't think this is the case because it seems to work properly in jLEMS... but maybe jLEMS is just more forgiving.

I'm using the latest version of PyLEMS that I just cloned from GitHub today, Python 2.7.6 on Ubuntu 14.04.

**Comment by sanjayankur31** [comment]
Still reproducible, looking into this now.

**Comment by sanjayankur31** [comment]
@pgleeson : I tracked this down. The issue is here in the `do_startup` method:

https://github.com/LEMS/pylems/blob/development/lems/sim/runnable.py#L539

Here, the `startup_event_handlers` are run before the first `update_derived_variables` call. So even though the `run_startup_event_handler` code does correctly include `self.v = self.initMembPot`, the `self.initMembPot = (self.biophysicalProperties.membraneProperties.initMembPotential.value)` statement has not yet been called. So, the fix would be simply to update the ordering of the calls to the handlers there to call `run_startup_event_handlers` after `update_derived_variables`. I think that makes sense, since in Cells.xml, the `initMembPot` `DerivedVariable` needs to have picked up its value before it is used to initialise `v`?

Here's the generated code for the two handlers:

```
------------- run_startup_event_handlers, cell1_sim1, ['initMembPot', 'thresh', 'surfaceArea', 'totSpecCap', 'iChannels', 'iSyn', 'iCa', 'caConc', 'caConcExt', 'totCap'] ----------------
def __generated_function__(self):
    if "xxx" in "run_startup_event_handlers": print("Calling method: run_startup_event_handlers(), dv: ['initMembPot', 'thresh', 'surfaceArea', 'totSpecCap', 'iChannels', 'iSyn', 'iCa', 'caConc', 'caConcExt', 'totCap'], iv: ['v', 'spiking']")
    self.spiking = 0
    self.v = self.initMembPot
```

```
------------- update_derived_variables, cell1_sim1, ['initMembPot', 'thresh', 'surfaceArea', 'totSpecCap', 'iChannels', 'iSyn', 'iCa', 'caConc', 'caConcExt', 'totCap'] ----------------
def __generated_function__(self):
    if "xxx" in "update_derived_variables": print("Calling method: update_derived_variables(), dv: ['initMembPot', 'thresh', 'surfaceArea', 'totSpecCap', 'iChannels', 'iSyn', 'iCa', 'caConc', 'caConcExt', 'totCap'], iv: ['v', 'spiking']")
    self.initMembPot = (self.biophysicalProperties.membraneProperties.initMembPotential.value)
    self.thresh = (self.biophysicalProperties.membraneProperties.spikeThresh.value)
    self.surfaceArea = 0
    self.surfaceArea_shadow = 0
    try:
        acc = 0
        for o in self.morphology.segments:
            acc = acc + o.surfaceArea
        self.surfaceArea = acc
        self.surfaceArea_shadow = acc
    except:
        pass
    self.totSpecCap = (self.biophysicalProperties.totSpecCap)
    self.iChannels = (self.biophysicalProperties.membraneProperties.totChanCurrent)
    self.iSyn = 0
    self.iSyn_shadow = 0
    try:
        acc = 0
        for o in self.synapses:
            acc = acc + o.i
        self.iSyn = acc
        self.iSyn_shadow = acc
    except:
        pass
    self.iCa = (self.biophysicalProperties.membraneProperties.iCa)
    self.caConc = (self.biophysicalProperties.intracellularProperties.caConc)
    self.caConcExt = (self.biophysicalProperties.intracellularProperties.caConcExt)
    self.totCap = ((self.totSpecCap) * (self.surfaceArea))

```
